import { StyleSheet } from 'react-native'
import { fontFamily } from '../font-family'
import { colors } from '../colors'

export const s = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: '#F2F4F7',
		alignItems: 'center',
		paddingVertical: 30,
		height: '100%',
	},
	text: {
		fontSize: 20,
		fontFamily: fontFamily.bold,
		textAlign: 'center',
	},
	flatlist: {
		width: '100%',
		marginHorizontal: 10,
		backgroundColor: '#FFFFFF',
		borderRadius: 10,
		shadowColor: '#FFFFFF',
		shadowOffset: { width: 0, height: 1 },
		shadowOpacity: 0.4,
		shadowRadius: 2,
		elevation: 3,
	},
	containerItemProfile: {
		flexDirection: 'column',
		width: '100%',
	},
	separator: {
		width: '100%',
		height: 8,
		backgroundColor: '#F2F4F7',
	},
	item: {
		backgroundColor: '#FFFFFF',
		paddingVertical: 10,
		paddingHorizontal: 20,
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
		gap: 10,
		shadowColor: '#FFFFFF',
		shadowOffset: { width: 0, height: 1 },
		shadowOpacity: 0.4,
		shadowRadius: 2,
		elevation: 3,
	},
	itemProfile: {
		paddingHorizontal: 15,
		flexDirection: 'column',
	},
	title: {
		fontSize: 16,
		fontFamily: fontFamily.bold,
	},
	description: {
		fontFamily: fontFamily.regular,
		fontSize: 13,
		color: colors.gray[500],
	},
	image: {
		width: 35,
		height: 35,
		borderRadius: 35,
		backgroundColor: colors.main.base,
		justifyContent: 'center',
		alignItems: 'center',
	},
	middle: {
		flex: 1,
		width: '100%',
		justifyContent: 'space-between',
	},
	notificationBody: {
		width: '100%',
		gap: 5,
	},
	right: {
		fontFamily: fontFamily.bold,
		color: colors.main.base,
		fontSize: 14,
	},
	fallback: {
		textAlign: 'center',
		fontFamily: fontFamily.bold,
		fontSize: 14,
		color: '#FFFFFF',
	},
	containerButton: {
		flexDirection: 'row',
		gap: 20,
		marginRight: 5,
		padding: 6,
		backgroundColor: '#FFFFFF',
		borderRadius: 30,
	},
	containerProfile: {
		width: '100%',
		alignItems: 'center',
		flexDirection: 'column',
		gap: 10,
	},
	avatar: {
		width: 80,
		height: 80,
		borderRadius: 100,
		borderWidth: 2,
		borderColor: '#F2F4F7',
		justifyContent: 'center',
		alignItems: 'center',
	},
	profileImage: {
		width: 80,
		height: 80,
		borderRadius: 100,
		borderWidth: 2,
		borderColor: '#F2F4F7',
		justifyContent: 'center',
		alignItems: 'center',
		opacity: 0.8,
		backgroundColor: 'rgba(0, 0, 0, 0.9)',
	},
	containerImageIcon: {
		backgroundColor: colors.main.base,
		padding: 5,
		borderRadius: 30,
		width: 30,
		height: 30,
		justifyContent: 'center',
		alignItems: 'center',
		position: 'absolute',
		bottom: 0,
		right: 0,
	},
	username: {
		fontSize: 16,
		fontFamily: fontFamily.bold,
	},
	email: {
		fontSize: 14,
		fontFamily: fontFamily.regular,
		color: colors.gray[400],
	},
	rightProfile: {
		flex: 1,
		flexDirection: 'row',
		justifyContent: 'flex-start',
		alignItems: 'center',
		gap: 10,
	},
	titleItemProfile: {
		fontSize: 16,
		fontFamily: fontFamily.regular,
	},
	containerHome: {
		flex: 1,
		backgroundColor: '#F5F5F5',
		paddingVertical: 15,
		paddingHorizontal: 20,
	},
	headerHome: {
		flex: 1,
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
		padding: 10,
		borderRadius: 10,
		backgroundColor: '#FFFFFF',
		shadowColor: '#000000',
		shadowOffset: { width: 0, height: 1 },
		shadowOpacity: 0.4,
		shadowRadius: 2,
		marginVertical: 20,
		marginHorizontal: 10,
		elevation: 5,
		gap: 5,
	},
	searchHome: {
		flex: 1,
		borderRadius: 100,
		backgroundColor: '#F2F4F7',
		fontFamily: fontFamily.regular,
		height: '100%',
		width: '100%',
		padding: 10,
		color: colors.gray[500],
	},
	itemHome: {
		marginHorizontal: 10,
		paddingVertical: 15,
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
		gap: 20,
		backgroundColor: '#FFFFFF',
		shadowColor: '#000000',
		shadowOffset: { width: 0, height: 1 },
		shadowOpacity: 0.4,
		shadowRadius: 2,
		elevation: 3,
		marginBottom: 10,
		borderRadius: 10,
	},
	postContainer: {
		width: '100%',
		backgroundColor: '#F2F4F7',
		paddingVertical: 30,
		borderWidth: 1,
		borderColor: colors.gray[200],
		marginBottom: 10,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
	},
	post: {
		fontSize: 16,
		fontFamily: fontFamily.bold,
		textAlign: 'center',
		color: colors.gray[500],
	},
	author: {
		flex: 1,
		flexDirection: 'row',
		gap: 5,
		alignItems: 'center',
		paddingHorizontal: 20,
	},
	authorAvatar: {
		width: 30,
		height: 30,
		borderRadius: 100,
		backgroundColor: colors.main.transparent,
		justifyContent: 'center',
		alignItems: 'center',
	},
	postFooter: {
		flexDirection: 'column',
		justifyContent: 'space-between',
		paddingHorizontal: 20,
		gap: 10,
	},
	postMessageButton: {
		marginRight: 15,
	},
	chatContainer: {
		flex: 1,
		padding: 10,
		backgroundColor: '#F2F4F7',
	},
	chatView: {
		padding: 10,
		borderRadius: 10,
		marginVertical: 5,
		maxWidth: '70%',
	},
	chatFooter: {
		flexDirection: 'row',
		alignItems: 'flex-end',
		padding: 10,
		backgroundColor: '#fff',
		justifyContent: 'center',
		borderRadius: 8,
		shadowColor: '#000000',
		shadowOffset: { width: 0, height: 1 },
		shadowOpacity: 0.4,
		shadowRadius: 2,
		elevation: 3,
	},
	chatInput: {
		flex: 1,
		borderWidth: 1,
		borderColor: '#ccc',
		borderRadius: 30,
		padding: 10,
		fontFamily: fontFamily.regular,
	},
	chatButton: {
		marginLeft: 10,
		backgroundColor: colors.main.base,
		padding: 8,
		borderRadius: 50,
	},
	message: {
		fontFamily: fontFamily.regular,
		fontSize: 15,
		color: colors.gray[500],
	},
	label: {
		fontSize: 14,
		marginBottom: '2%',
		fontFamily: fontFamily.bold,
	},
	input: {
		width: '100%',
		borderWidth: 1,
		borderColor: colors.gray[400],
		borderRadius: 10,
		padding: '4%',
		marginBottom: '3%',
		color: colors.gray[600],
		fontFamily: fontFamily.regular,
		fontSize: 14,
	},
	error: {
		color: colors.main.light,
		fontSize: 12,
		fontFamily: fontFamily.regular,
		textAlign: 'right',
		marginTop: -5,
	},
})
